---
- name: Install MySQL prod
  hosts: prod
  sudo: yes
  sudo_user: root
  remote_user: "{{remote_user}}"
  vars:
    update_apt_cache: yes
    kernel_shmmax: 5368709120
    shared_buffers: 3840MB
    effective_cache_size: 7680MB
    work_mem: 32MB
    maintenance_work_mem: 1024MB
    checkpoint_segments: 32
    checkpoint_completion_target: 0.9
    innodb_buffer_pool_size: 512M #/!\ t2.micro volume = 8G MAX
    innodb_buffer_pool_instances: 5
  # vars_files:
  #   - env_vars/noodleapi/prod.yml
  roles:
    # - base 
    - mysql