---
- name: Provision a MySQL stage server
  hosts: "{{ hosts }}"
  sudo: yes
  sudo_user: root
  remote_user: "{{remote_user}}"
  vars:
    update_apt_cache: yes
    kernel_shmmax: 5368709120
    shared_buffers: 3840MB
    effective_cache_size: 7680MB
    work_mem: 32MB
    maintenance_work_mem: 1024MB
    checkpoint_segments: 32
    checkpoint_completion_target: 0.9
    innodb_buffer_pool_size: 10G
    innodb_buffer_pool_instances: 5
  vars_file:
    - env_vars/noodleapi/consistent.yml
  roles:
    - base
    - mysql