#Create my-security-group-test
---
- name: Create security group
  local_action: 
    description: "Access to the {{server_env}} servers"
    module: ec2_group
    name: "{{security_group}}"
    region: "{{region}}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        from_port: 22
        to_port: 22
    rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0