---

- name: Install MySQL package
  apt: name=mysql-server update_cache={{ update_apt_cache }} state=installed

- include: setup.yml
  when: setup_mysql

- name: Copy .my.cnf file with root password credentials
  template: src=root/.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  notify: restart mysql
  tags: mysqlconfig

- name: Ensure the MySQL service is started
  service: name=mysql state=started enabled=yes

# Note that 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: Update mysql root password for all root accounts
  mysql_user: login_user=root
              login_password=''
              name=root
              host={{ item }}
              password={{ mysql_root_password }}
              priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: yes

- name: Delete anonymous MySQL server user
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - "{{ inventory_hostname }}"

- name: Remove the MySQL test database
  mysql_db: db=test state=absent

- include: setup_database.yml
  when: setup_database
