---

- name: Ensure MySQL server is stopped
  service: name=mysql state=stopped

- name: Copy custom my.cnf file
  template: src={{ mysql_config_template }}
            dest=/etc/mysql/my.cnf
            owner=root
            group=root
            mode=0644
            backup=yes
  notify: restart mysql
  tags: mysqlconfig

#We don't need to use a custon usr.sbin.mysqld file
#We don't need to restart apparmor => We don't change the datadir

- name: Ensure MySQL server is started
  service: name=mysql state=started
