---

- name: Ensure MySQL server is stopped
  service: name=mysql state=stopped

- name: Copy custom my.cnf file
  template: src={{ mysql_config_template }}
            dest=/etc/mysql/my.cnf
            owner=root
            group=root
            mode=0644
            backup=yes
  notify: restart mysql
  tags: mysqlconfig

- name: Copy custom usr.sbin.mysqld file
  template: src=usr.sbin.mysqld.j2
            dest=/etc/apparmor.d/usr.sbin.mysqld
            owner=root
            group=root
            mode=0644
            backup=yes

- name: Restart apparmor
  service: name=apparmor state=restarted

- name: Initialize the new data directory
  command: mysql_install_db --user=mysql --datadir=/var/lib/mysql

- name: Ensure MySQL server is started
  service: name=mysql state=started
